### PR TITLE
Reverts Breaking Changes for a Patch Release

### LINKED ISSUE #32: Breaking change with major release
This change https://github.com/ianstormtaylor/css-color-function/commit/9334b306bef20ab1b0a61706cce222ee3bfb2ed6 is breaking change and it is very sensitive without ChangeLog.

Maybe we can add ChangeLog? Or some warning?

### PR DESCRIPTION
**Pull request by tylergaw**
fixes #32 

As noted in that issue breaking changes were made in #19. The idea was to release those in a 2.0, but I missed that and ended up releasing them in 1.3.1.

This PR removes those changes for a quick 1.3.3. This release will include the updates in #26 and #31.

### CODE REVIEW

**Comment by tylergaw** [comment]
@ai Does this seem correct?

**Comment by ai** [comment]
Yeap, great!

**Comment by ai** [comment]
BTW, also we can in 2.0 you can add `color-mod()` func name since spec was changed.

**Comment by tylergaw** [comment]
Cool, thanks.

On `color-mod` I'm still confused on the spec. I mentioned in this issue https://github.com/ianstormtaylor/css-color-function/issues/29 that the naming is unclear. I wonder if the spec just needs updated still? Wonder if @tabatkins could shed some light on that for us?

**Comment by tabatkins** [comment]
Basically ignore the `color-mod()` function for now. It needs to be substantially revamped.

**Comment by ai** [comment]
@tabatkins thanks!

**Comment by tylergaw** [comment]
Excellent, thanks @tabatkins!

OK, I'm going to go ahead and merge / release this. Then follow it up with the 2.0 release we discussed.

**Pull request merged**
