### PR TITLE
Require space after + and - modifiers

### PR DESCRIPTION
**Pull request by taion**
Fixes https://github.com/ianstormtaylor/css-color-function/issues/18

I hate this modifier syntax, BTW.

### CODE REVIEW

**Comment by MoOx** [comment]
Specs say
 
> Note: While scaling can be specified without any spaces, like lightness(*150%), adding/subtracting must be done with spaces after the +/-, or else the +/- will be interpreted as part of the number by the CSS parser.

So this PR lgtm.

**Comment by kinday** [comment]
Sorry for long response. PR looks good to me. Also thanks for fixing tests and typos.

**Comment by taion** [comment]
I wonder if it would make sense to have a loose mode.

**Comment by taion** [comment]
(Really more for postcss-color-function, cc @MoOx)

**Comment by kinday** [comment]
I love the way PostCSS approaches the future. The loose mode is not spec-friendly. There will be the day when the feature would shine green but you won’t be able to throw away PostCSS plugin without breaking your code.

**Comment by MoOx** [comment]
Not a problem for me neither. I will cut a release with a breaking change.

**Comment by taion** [comment]
Did this ever get released, BTW?

**Pull request merged**
